  spring:
    jpa :
      database  : MYSQL
      show-sql  : true
      hibernate :
        ddl-auto: update
    datasource  :
      drivername: com.mysql.jdbc.Driver
      url       : jdbc:mysql://localhost/explore
      username  : root
      password  : root

  server:
    port : 8181
